### ISSUE TITLE
Getting this error when execute 

### ISSUE THREAD

**Issue by patdha86** [f5regan/o365-apm-split-tunnel#2]
Due to not having enough scripting knowledge I got stuck at initail stage. Can you please help?

F5::Active:Changes Pending#python /shared/o365/apm_o365_update.py

File "/shared/o365/apm_o365_update.py", line 526

    ^
SyntaxError: invalid syntax

Do I need to change permission for this file? Please advice.

**Comment by f5regan** [comment]
Hello, you shouldn't need to change the permissions on the file. Can you confirm that you correctly imported the script to your BIG-IP? The script only has 392 lines so a syntax error on line 526 seems odd.

**Comment by patdha86** [comment]
Here is how I imported. 
cat > apm_o365_update.py
[copy and paste code here, modify user option]
Ctrl + C

**Comment by patdha86** [comment]
Open the script in raw format, copy and paste,  modify user option and it works....OMG 
Thank you so much!

**Comment by patdha86** [comment]
I have this setting applied for Network Access List. After applying exclude list I no longer able to connect. Anything looks abnormal here?  ![image](https://user-images.githubusercontent.com/62904997/77955981-5417f480-728e-11ea-89eb-3d2ea428accc.png)

**Comment by patdha86** [comment]
Remaingin half of screenshot 
![image](https://user-images.githubusercontent.com/62904997/77956192-b3760480-728e-11ea-8504-86d4333e821d.png)

**Comment by f5regan** [comment]
Glad to hear you got the script working! As to why the split tunnel isn't working I won't be able to provide much assistance to you there. You might want to check out the DevCentral community or engage F5 Support to try and figure out why that is.

That said, I have one idea of a potential cause for the failure. Is it possible that your client is resolving an IPV6 address for O365? If your client resolves and attempts to connect to an IPV6 O365 address and your Network Access List is not configured with IPV6 split tunneling I think the O365 connection will fail.

I'm closing this issue as the script appears to be functioning properly.
